baseURL = "https://xieweialex.github.io/"
languageCode = "en-us"
title = "Alex's personal blog"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
ignoreErrors = ["error-output-taxonomy"]

[markup.goldmark.renderer]
  unsafe = true # Allow user HTML tags

[params]
  author = "Alex Xie"
  github = "xieweiAlex"
  twitter = "xiewei_alex"
  email = "alex.xie2016@gmail.com"
  avatar = "avatar.jpg"
  favicon = "favicon.ico"
  description = """
This is my personal blog where I collect and make sense of my thoughts, it also allows me to practice my English writing skills. It's a great way to kill two birds with one stone! 😄
  """
  publicationYear = "2024"

[outputs]
  section = ["JSON", "HTML"]
  taxonomy = ["JSON", "HTML"]

[[menu.main]]
  identifier = "blog"
  name = "Blog" 
  pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
  url = "/post/"
  weight = 10

[[menu.main]]
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class='fab fa-twitter fa-lg'></i>"
  url = "https://twitter.com/xiewei_alex"
  weight = 20

[[menu.main]]
  identifier = "github"
  name = "GitHub"
  pre = "<i class='fab fa-github fa-lg'></i>"
  url = "https://github.com/xieweiAlex"
  weight = 30

[[menu.main]]
  identifier = "email"
  name = "Email"
  pre = "<i class='fa fa-envelope fa-lg'></i>"
  url = "mailto:alex.xie2016+blog@gmail.com"
  weight = 50



